### ISSUE TITLE
Supporting multiple channels in cloud infrastructure

### ISSUE THREAD

**Issue by FoxBravoNL** [aws-samples/amazon-ivs-dvr-web-demo#10]
Hi there,

I'm using this example as a basis for an iOS app that implements AWS IVS livestreaming and VOD playback. Especially the easy switching between live and VOD is ideal for our purposes and this is already working well using this demo setup.

In this example only one stream channel is created with the corresponding S3 buckets and Cloudfront setup. I'm trying to figure out how to use this setup to support up to 6 streams that will be running simultaneously (6 camera angles). Can someone point me in the right direction on where the start editing the files to create multiple streams? And will this work through one Cloudfront distribution or should there also be multiple configurations setup in Cloudfront?

Many thanks!
Fabian

**Comment by andreido** [comment]
Hello @FoxBravoNL, thank you for opening this issue!

This feature is outside of the scope of this demo, and would require re-architecting the backend. However, most of the current architecture can likely be kept intact, with the majority of the work required being to manage multiple IVS channels and the destinations of their recorded content in the S3 bucket. Here are some steps you can consider taking to point you in the right direction.

Firstly, given that the same recording configuration can be used to save recordings from multiple IVS channels to the same S3 bucket, we should expect there to be a path in our S3 bucket for each of these IVS channels. Upon starting a live stream for each of these IVS channels, the S3 event notification will be fired for each one and trigger the `saveRecordingStartMeta` Lambda function. Whereas previously this Lambda function saved the latest `recording-started.json` file for a single IVS channel, it will need to be modified to do the same for all our IVS channels and name each of these files accordingly.

Additionally, the `getLatestRecordingStartMeta` Lambda function will also need to be modified to return the recording metadata specific to a particular IVS channel, as opposed to just the one that we have today.

Lastly, while the same CloudFront distribution can be used to support multiple IVS channels, the `/recording-started-latest.json` behavior pattern may need to be modified such that it covers the saved metadata file names for each of the IVS channels in question.

The outputs of this new stack should now expose the `ingestServer`, `streamKey` and `playbackUrl` for each of the IVS channels.

**Comment by FoxBravoNL** [comment]
Thanks for taking the time @andreido !! Since it's been quite a while when I posted this, I've actually managed to get it to work using multiple channels using the exact same steps as you outlined! :)
